### ISSUE TITLE
Copy Method Errors When Building Project Resources

### ISSUE THREAD

**Issue by tonyjunkes** [Ortus-Solutions/coldbox-elixir#16]
I created a project based on the ColdBox Elixir template and attempted to build the resources after pulling in all the dependencies.

The error is as follows:

```
Invalid options object. Copy Plugin has been initialized using an options object that does not match the API schema.
 - options[0] misses the property 'patterns'.
```

After reviewing the error and `copy-webpack-plugin` docs, it would appear that in newer versions of the library, the param object being passed requires a property name of `patterns`.

For example:

```
new CopyPlugin({ patterns: [ { from: 'source', to: 'dest' } ] });
```

After, applying this change to my local install of `coldbox-elixir`, the project built successfully and the file(s) appeared as expected.

I can file a PR if desired but, I wanted to bring this up first in case I missed something regarding the existing usage of the feature.

**Comment by elpete** [comment]
I think we may be installing a newer version than we expected.

This line here is not constrained at all, so that's likely the problem.

https://github.com/Ortus-Solutions/coldbox-elixir/blob/cc785407ed0fc151d29087fe1ffc252b80364843/src/config/ingredients/copy.js#L4

In either case we need to restrict the version going forward.  If you want to do that either with or without updating it, that would be great.  Thanks!

**Comment by tonyjunkes** [comment]
No problem. I'll see about getting that sorted in the next few days.
